//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fines
    {
        public int id { get; set; }
        public Nullable<int> reader_id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> days_overdue { get; set; }
        public Nullable<decimal> fine_amount { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Readers Readers { get; set; }
    }
}
