//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int FileID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public byte[] FileData { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int UploadedBy { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
