//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutgoingInvoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OutgoingInvoices()
        {
            this.OutgoingInvoiceItems = new HashSet<OutgoingInvoiceItems>();
        }
    
        public int InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime DateShipped { get; set; }
        public int ClientID { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutgoingInvoiceItems> OutgoingInvoiceItems { get; set; }
    }
}
