//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogs
    {
        public int LogID { get; set; }
        public int UserID { get; set; }
        public string Action { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
