//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingInvoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncomingInvoices()
        {
            this.IncomingInvoiceItems = new HashSet<IncomingInvoiceItems>();
        }
    
        public int InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime DateReceived { get; set; }
        public int SupplierID { get; set; }
        public decimal TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingInvoiceItems> IncomingInvoiceItems { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
