//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryResults
    {
        public int ResultID { get; set; }
        public int InventoryID { get; set; }
        public int ProductID { get; set; }
        public int ActualQuantity { get; set; }
        public int RecordedQuantity { get; set; }
        public int Difference { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Products Products { get; set; }
    }
}
