//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WarehouseManagementEntities : DbContext
    {
        public WarehouseManagementEntities()
            : base("name=WarehouseManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barcodes> Barcodes { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<IncomingInvoiceItems> IncomingInvoiceItems { get; set; }
        public virtual DbSet<IncomingInvoices> IncomingInvoices { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<InventoryResults> InventoryResults { get; set; }
        public virtual DbSet<OutgoingInvoiceItems> OutgoingInvoiceItems { get; set; }
        public virtual DbSet<OutgoingInvoices> OutgoingInvoices { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StorageZones> StorageZones { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserLogs> UserLogs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
    }
}
