//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenditureInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenditureInvoice()
        {
            this.ExpenditureInvoiceWarehouse = new HashSet<ExpenditureInvoiceWarehouse>();
        }
    
        public int IdExpenditureInvoice { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public double TotalPrice { get; set; }
        public int IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenditureInvoiceWarehouse> ExpenditureInvoiceWarehouse { get; set; }
    }
}
