//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncomingInvoice()
        {
            this.IncomingInvoiceWarehouse = new HashSet<IncomingInvoiceWarehouse>();
        }
    
        public int IdIncomingInvoice { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime DateReceipt { get; set; }
        public int IdSupplier { get; set; }
        public double TotalPrice { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingInvoiceWarehouse> IncomingInvoiceWarehouse { get; set; }
    }
}
