//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingInvoiceWarehouse
    {
        public int IdIncomingInvoiceWarehouse { get; set; }
        public int IdIncomingInvoice { get; set; }
        public int IdWarehouse { get; set; }
    
        public virtual IncomingInvoice IncomingInvoice { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
