//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryWarehouse
    {
        public int IdInventoryWarehouse { get; set; }
        public int IdIntentory { get; set; }
        public int IdWarehouse { get; set; }
        public double AccountingQuantity { get; set; }
        public double ActualQuantity { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
