//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.NewFolder1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Складской_учетEntities : DbContext
    {
        public Складской_учетEntities()
            : base("name=Складской_учетEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<ExpenditureInvoice> ExpenditureInvoice { get; set; }
        public virtual DbSet<ExpenditureInvoiceWarehouse> ExpenditureInvoiceWarehouse { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<GoodsWarehouse> GoodsWarehouse { get; set; }
        public virtual DbSet<IncomingInvoice> IncomingInvoice { get; set; }
        public virtual DbSet<IncomingInvoiceWarehouse> IncomingInvoiceWarehouse { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<InventoryWarehouse> InventoryWarehouse { get; set; }
        public virtual DbSet<StorageArea> StorageArea { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
        public virtual DbSet<WarehouseType> WarehouseType { get; set; }
    }
}
