//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouse()
        {
            this.ExpenditureInvoiceWarehouse = new HashSet<ExpenditureInvoiceWarehouse>();
            this.GoodsWarehouse = new HashSet<GoodsWarehouse>();
            this.IncomingInvoiceWarehouse = new HashSet<IncomingInvoiceWarehouse>();
            this.InventoryWarehouse = new HashSet<InventoryWarehouse>();
        }
    
        public int IdWarehouse { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public int IdWarehouseType { get; set; }
        public int IdStorageArea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenditureInvoiceWarehouse> ExpenditureInvoiceWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsWarehouse> GoodsWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingInvoiceWarehouse> IncomingInvoiceWarehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryWarehouse> InventoryWarehouse { get; set; }
        public virtual StorageArea StorageArea { get; set; }
        public virtual WarehouseType WarehouseType { get; set; }
    }
}
